== Culture & People

=== Why?

* Since I can remember I have been unhappy with the default culture of this world. 
* Though I searched in mayn different places, I ultimately find the answers to my brokeness and the brokeness of the World in Christ
* Tripattern exists to help people to see there is a way out of their brokeness
** It may start as simply solving an acute problem they have, but ultimately the idea is to open and prepare their hearts to encounter Jesus!
* This is why!!!

=== Values & Principles

* 
* 
* 

=== The right kind of people...

The type of people I want to build with and partner with are:

*Courageous:*
Not afraid to try out whacky ideas, but yet also disciplined and focused enough to run an experiement through and evaluate the results objectively

*Humble & Inquisitive:*
Don't think they know everything, and are not afraid to make mistakes and perhaps look a little foolish

*Servanthearted:*
Seeking to serve and not be served

*Desire to build up others:*

*Forgive easily, compassionate, gracious and merciful:*

