= Scrumban for the Kingdom

== Why?
What follows is an approach to leading a team or family concerned with following the Trinity in the path of discipleship.

== Pillars
* Transparency / Openness
** We want to create an open environment in our leadership team
* Inspect / Sense
** Whenever we do something we want to take time to sense in the Spirit if we are going in the right direction
** This would include praying together for feedback not just guidance from the Holy Spirit
* Adaptation
** Based on what we observe and sense we want to make changes to what we do as a group except we want to be careful that we don't grieve the Spirit and do things contrary to our sense of what the Scriptures say.

== Values
* Kingdom, where foundational are:
** Love
** Faith
** Hope
* Scrum, subset:
** Commitment
*** together achieving the goals of the kingdom provided by the Holy Spirit and Scripture
*** Supporting each other in the process
** Focus
*** The main focus of the activity in the Sprint is to make progress toward the Trinity's goals 
** Openness
*** The team members and stakeholders need to be open about the challenges of this work and 
** Respect
*** We respect the gifting and capability of each member of the team
** Courage

