= Creed

== My Personal Creed

I believe in God the Father (Abba), God the Son (Yeshua) and God the Holy Spirit (Ruach).
They are a perfect unity, yet three persons.
I believe together they created the universe as described in Genesis in 6 days.
I believe they rested on the 7th day.
I believe that Adam & Eve were created by God and I believe they both ate from the forbidden tree through which sin entered the universe.

I believe that God through the line of Seth, Noah, Abraham, Isaac and Jacob formed the nation of Israel providing them with His perfect law.
The law being used to prepare Israel and ultimately the universe for the coming of the Messiah: Yeshau, the Son of God and himself God.

Yeshua was conceived of the Holy Spirit, was born of the virgin Mary, lived a blameless life, called and taught the first Disciples
and died as the perfect sacrificial lamb taking all the sins of the World upon Himself.
On the 3rd day He rose again, witnessed by many and after 40 days was taken up into heaven, and is seated on the right hand of the Father: He shall come again with glory to judge the living and the dead, and His kingdom shall have no end.

He poured out the Spirit (Ruach) on those who believed and who still believe in Him and through his people with the power of the Spirit (Ruach) signs and wonders are carried out in faith preparing the World for the return of the King and destroying the works of the enemy in each age until the end and the final day of judgement comes.

I accordingly believe in 2 Baptisms that are an important part of every believers path in following Christ.
Baptism in water signifying that the old man has died and that the new man has been birthed in the believer.
Baptism of the Holy SPirit as shown in the Book of Acts. This should be accompanied with the speaking in other tongues.

I believe that the government of Heaven is the government of family and that as we see family expressed in the trinity so here on earth God has created male and female to become one flesh and to bring forth more children to extend the government of heaven on earth as it is in heaven.

I believe that the Church (Ecclesia) is the Body of Christ and it is to be governed as set in place by Paul by Elders and served by Deacons, but also by all who are a part of it, each one seeking to find there place of service in the Kingdom.


== References

=== The Apostles' Creed
I believe in God the Father Almighty, Maker of heaven and earth.
And in Jesus Christ, His only Son, our Lord; Who was conceived by the Holy Spirit; Born of the Virgin
Mary; Suffered under Pontius Pilate; Was crucified, dead and buried; He descended into Hell; The third
day He rose again from the dead; He ascended into heaven; And sitteth on the right hand of God the
Father Almighty; From thence He shall come to judge the living and the dead.
I believe in the Holy Spirit; The Holy Christian Church, the Communion of Saints; The Forgiveness of
sins; The Resurrection of the body; And the life everlasting. Amen.


=== The Nicene Creed
I believe in one God, the Father almighty, maker of heaven and earth and of all things visible and
invisible.
And in one Lord Jesus Christ, the only-begotten Son of God, begotten of the Father before all ages, God
of God, Light of Light, very God of very God, begotten not made, being of one substance with the Father,
through Whom all things were made: Who for us men and for our salvation came down from heaven, was
incarnate by the Holy Spirit of the virgin Mary, and was made man: Who for us, too, was crucified under
Pontius Pilate, suffered, and was buried: the third day He rose according to the Scriptures, ascended into
heaven, and is seated on the right hand of the Father: He shall come again with glory to judge the living
and the dead, and His kingdom shall have no end.
And in the Holy Spirit, the Lord and Giver of life, Who proceeds from the Father and the Son: Who
together with the Father and the Son is worshiped and glorified: Who spoke by the prophets.
And I believe one holy, Christian, and apostolic Church.
I acknowledge one baptism for the remission of sins, and I look for the resurrection of the dead and life of
the age to come.
Amen.

=== The Athanasian Creed
Whoever wishes to be saved must, above all else, hold the true Christian faith. Whoever does not keep it
whole and undefiled will without doubt perish for eternity.
This is the true Christian faith, that we worship one God in three Persons and three Persons in one God
without confusing the Persons or dividing the divine substance.
For the Father is one Person, the Son is another, and the Holy Spirit is still another, but there is one
Godhead of the Father and of the Son and of the Holy Spirit, equal in glory and coequal in majesty.
What the Father is, that is the Son and that is the Holy Spirit: the Father is uncreated, the Son is
uncreated, the Holy Spirit is uncreated; the Father is unlimited, the Son is unlimited, the Holy Spirit is
unlimited; the Father is eternal, the Son is eternal, the Holy Spirit is eternal; and yet They are not three
Eternals but one Eternal, just as there are not Three Who are uncreated and Who are unlimited, but there
is One who is uncreated and unlimited.
Likewise the Father is almighty, the Son is almighty, the Holy Spirit is almighty.
So the Father is God, the Son is God, the Holy Spirit is God, and yet there are not three Gods but one
God.
So the Father is Lord, the Son is Lord, the Holy Spirit is Lord, and yet they are not three Lords but one
Lord.
For just as we are compelled by Christian truth to acknowledge each Person by Himself to be God and
Lord, so we are forbidden by the Christian religion to say that there are three Gods or three Lords.
The Father was neither made nor created nor begotten by anybody.
The Son was not made or created, but was begotten by the Father.
The Holy Spirit was not made or created or begotten, but proceeds from the Father and the Son.
Accordingly there is one Father and not three Fathers, one Son and not three Sons, one Holy Spirit and
not three Holy Spirits.
And among these three Persons none is before or after another, none is greater or less than another, but all
three Persons are coequal and coeternal, and accordingly, as has been stated above, three Persons are to be
worshiped in one Godhead and one God is to be worshiped in three Persons.
Whoever wishes to be saved must think thus about the Trinity.
It is also necessary for eternal salvation that one faithfully believe that our Lord Jesus Christ became man,
for this is the right faith, that we believe and confess that our Lord Jesus Christ, the Son of God, is at once
God and man:
He is God, begotten before the ages of the substance of the Father, and He is man, born in the world of
the substance of His mother, perfect God and perfect man, with reasonable soul and human flesh, equal to
the Father with respect to his Godhead and inferior to the Father with respect to His manhood.
Although he is God and man, He is not two Christs but one Christ: one, that is to say, not by changing the
Godhead into flesh, but by taking on the humanity into God, one, indeed, not by confusion of substance
but by unity in one Person.
For just as the reasonable soul and the flesh are one man, so God and man are one Christ, Who suffered
for our salvation, descended into hell, rose from the dead, ascended into heaven, is seated on the right
hand of the Father, whence He shall come to judge the living and the dead.
At His coming all men shall rise with their bodies and give an account of their own deeds.
Those who have done good will enter eternal life, and those who have done evil will go into everlasting
fire.
This is the true Christian faith. Unless a man believe this firmly and faithfully, he cannot be saved. 

=== Biblical Confessions of Faith
"Now I make known to you, brethren, the gospel which I preached to you, which also you received, in
which you stand, by which also you are saved, if you hold fast the word which I preached to you, unless
you believed in vain. For I delivered to you as of first importance what I also received, that Christ died
for our sins according to the Scriptures, and that He was buried, and that He was raised on the third day
according to the Scriptures, and that He appeared to Cephas, then to the twelve. After that He appeared to
more than five hundred brethren at one time, most of whom remain until now, but some have fallen
asleep; than He appeared to James, then to all the apostles; and last of all, as it were to one untimely born,
He appeared to me also." I Corinthians 15:1-8
"And it came about that as I as on my way, approaching Damascus about noontime, a very bright light
suddenly flashed from heaven all around me, and I fell to the ground and heard a voice saying to me,
'Saul, Saul, why are you persecuting Me?' And I answered, 'Who art Thou, Lord?' And He said to me, 'I
am Jesus the Nazarene, whom you are persecuting.' And those who were with me beheld the light, to be
sure, but did not understand the voice of the One who was speaking to me. And I said, 'What shall I do,
Lord?' And the Lord said to me, 'Arise and go on into Damascus, and there you will be told of all that has
been appointed for you to do.' But since I could not see because of the brightness of the light, I was led
by the hand by those who were with me, and came into Damascus. And a certain Ananias, a man who
was devout by the standard of the Law, and well spoken of by all the Jews who lived there, came to me,
and standing near said to me, 'Brother Saul, receive your sight!' And at that very time I looked up at him.
And he said, 'The God of our fathers has appointed you to know His will, and to see the Righteous One,
and to hear an utterance from His mouth. For you will be a witness for Him to all men of what you have
seen and heard.'" Acts 22:6-15
"The God who made the world and all things in it, since He is Lord of heaven and earth, does not dwell in
temples made with hands; neither is He served by human hands, as though He needed anything, since He
Himself gives to all life and breath and all things; and He made from one, every nation of mankind to live
on all the face of the earth, having determined their appointed times, and the boundaries of their
habitation, that they should seek God, if perhaps they might grope for Him and find Him, though He is
not far from each one of us; for in Him we live and move and exist, as even some of your own poets have
said, 'For we also are His offspring.'" Acts 17:24-28 
