== Psychology / Biblical Counseling
https://www.thegospelcoalition.org/topics/psychology-and-disorders/
https://www.thegospelcoalition.org/article/christian-reflections-on-mental-disorder/

https://www.thegospelcoalition.org/?s=nouthetic
https://www.thegospelcoalition.org/reviews/biblical-counseling-movement-adams/
https://www.thegospelcoalition.org/reviews/biblical-counseling-movement/
https://www.thegospelcoalition.org/article/two-sides-of-the-counseling-coin/
https://www.thegospelcoalition.org/article/psychologist-biblical-counselor/

https://www.thegospelcoalition.org/themelios/review/psychology-and-christianity-five-views/

https://www.thegospelcoalition.org/reviews/keller-reexamine-worldview/

=== Biblical Counseling over Psychology
- Jay E. Adams
-- Competent to Counsel: Introduction to Nouthetic Counseling by Jay E. Adams
-- https://nouthetic.org/bookstore/#bookstore
-- https://www.cbuch.de/adams-seelsorge-mit-der-bibel.html

- https://www.thegospelcoalition.org/article/psychologist-biblical-counselor/
- Ernie Baker
-- Help! I'm In a Conflict (LifeLine Mini-books) (English Edition)
-- Biblical Counseling and The Psychologies (Critical Issues in Biblical Counseling)
- Counseling: How to Counsel Biblically (MacArthur Pastor's Library)

- https://biblicalcounseling.com/resource-library/articles/what-should-i-read-to-better-understand-biblical-counseling/

The Gospel and Mental Illness:
A Theology of Biblical Counseling by Heath Lambert:
A Theology of Christian Counseling by Jay Adams:
You Never Stop Being a Parent by Jim Newheiser and Elyse Fitzpatrick:

=== Christian Psychologist Authors
- Dr. Caroline Leaf
-- Switch on your Brain

- Alison Cook PhD - 
-- Boundaries for your soul
-- The best of you
-- I shouldn't feel this way

=== Depression

Hope Prevails: Insights from a Doctor’s Personal Journey Through Depression by Dr. Michelle Bengtson:
What to Do When You Don’t Know What to Do: Discouragement and Depression by Dr. Cloud and Dr. Townsend:
Five Keys to Dealing with Depression by Gregory Jantz:
Boundaries for Your Soul: How to Turn Your Overwhelming Thoughts and Feelings into Your Greatest Allies by Dr. Alison Cook:
Overcoming Depression by Neil Anderson (Victory Over the Darkness Series):

===  

=== World
- Mindset Carol S. Dweck
- The Psychology of Selling (Brian Tracy)

