== Honour one Another

=== Shameful Behaviour
Have you ever bothered to ask your spouse what is shameful behaviour for them?
What are things that cause them to cringe when they are with others?
Talk about things that they would prefer to discuss in private.
If a topic or issue comes up simply ask your spouse if you can discuss the issue at home together and get back to that person
on your combined decision.

=== Guard your Tongue

[quote, Proverbs 10:14 TPT]
____
Wise men don't divulge all that they know,
but chattering fools blurt out words
that bring them to the brink of ruin.
____

The pats of our bodies that are the most dangerous and which create the most destruction in a relationship is the tongue.
We ned to be so careful how we speak to each other and how we speak about our husbands or wives with others or when we are alone with others.
No one likes being in a relationship where the other person always wants to discuss everything in public (public includes anyone not a part of the relationship).
You guarda relationship in knowing when is the right time to discuss private matters.
People who supposedly try to be honest and open about everything do so perhaps at the cost of their loved one, leading to shame,
withdrawal and thoughts where the other will say to themselves,"I should probably never bring my wife or husband to... as I can't trust them to keep their mouth shut about our private lives."
You may think, but these are my friends, and I can be honest with them about our lives, but in so doing they blurt everything out.
What happens is that your spouse may think they can no longer trust you with any information and may begin to hold things back from you.
They may also feel completely ashamed and will avoid any situation with you that may lead to you opening about your relationship.
They will then seek to avoid going with you to any parties or functions etc. as they don't want something to suddenly come up that will lead to an akward situation.

Family, friends and colleagues may begin to avoid you as you may be seen to be gossipers or people with problems in their relationships.
This may close the door to community and the gospel for some: how dreadful if people thought that would not want to become a christian if they end up like you.
