= Women

== Wife

=== Are Men the Head over their wives?
Often a debate around the Word "kephale".
Another document of mine deals with this issue.




=== TODO
* https://www.touchstonemag.com/archives/article.php?id=05-04-005-f
* Science has found out that there are som ekey differences in our biology (over 30 years of peer reviewed research)
* https://torrancestephensphd.substack.com/p/i-follow-the-science-men-and-women
* https://www.historytoday.com/archive/review/disney-dreams
* https://www.youtube.com/watch?v=TKIC1O8uRAo
* History
** https://www.historytoday.com/history-matters/rise-working-wife
** https://www.historytoday.com/archive/history-matters/baby-boom-or-bust?utm_source=Weekly+Newsletter&utm_campaign=145701c121-EMAIL_CAMPAIGN_2017_09_20_COPY_01&utm_medium=email&utm_term=0_fceec0de95-145701c121-780674&mc_cid=145701c121&mc_eid=18852ba6f9

== Women in Ministry

=== TODO

=== Priscilla

[quote, Acts 18:24 - 28 KJV]
____
24 And a certain Jew named Apollos, born at Alexandria, an eloquent man, and mighty in the scriptures, came to Ephesus.

25 This man was instructed in the way of the Lord; and being fervent in the spirit, he spake and taught diligently the things of the Lord, knowing only the baptism of John.

26 And he began to speak boldly in the synagogue: whom when Aquila and Priscilla had heard, they took him unto them, and expounded unto him the way of God more perfectly.

27 And when he was disposed to pass into Achaia, the brethren wrote, exhorting the disciples to receive him: who, when he was come, helped them much which had believed through grace:

28 For he mightily convinced the Jews, and that publicly, shewing by the scriptures that Jesus was Christ.
____

Interesting to note that Priscilla's name is often mentioned first when they are referenced in the Bible.
This was unusual for the World at that time.
This may indicate that Priscilla had a more prominent role in the ministry they shared.
https://margmowczko.com/did-priscilla-teach-apollos/[Priscilla was involved in explaining]. I agree this is close to teaching, but perhaps in an informal way.
https://en.wikipedia.org/wiki/John_Chrysostom[John Chrysostom] wrote in the fourth century about Priscilla teaching Apopllos.
Note how Luke mentions Priscilla being involved in teaching Apollos in a very casual way.

== Women in the World

=== Business
* Proverbs 31
* The Household was the means of production

=== Politics
* Prophetess Hanna
* Don't believe this was a case of men not standing up and taking their role
