== New Covenant School Years
We left Midrand School & Church.
We joined NCCB & school.
Dreadful from the first day.
Best friend betrayed me.
My class rejected me from the beginning.
I took solace in German Nationalism and my fmaily history.

=== Fireworks Sunday
One Sunday in about 1990/1 a small incident took place that would affect my life for many years to come.
I had decided to take some left over fireworks from Guy Fawlkes to Church, to joke around after Sunday School.
I started letting them off and some of the girls started harassing me and saying that only little boys played with firecrackers and that this wasnÄt something grown ups did. Like only women can do with men, I became so furious I started throwing the firecrackers at the girls and in managed to get them to run away, frightened.

It could have simply ended that day, but it didn't.
For some reason this set off a tit for tat war that continued for all the time I was at that school.
During the week the girls would harass me with words and I would respond with actions on a Sunday.
