== Introduction

I would argue that your relational wealth is of greater importance than any other wealth you may have or are striving towards.
* No one has been successful who is not good at being relational
* Many people want a "no rules" workplace, but I argue unless you have a mature, healthy relational culutre this can't really become reality


We live in an age where the so called modern, progressive world has believed a deep lie.

It goes something like this:

* Pursue what is you want, feel like, desire
* Gather what is best for you
* Build your life around your wants and desires
** surround your life with the luxuries and interests that best fit you

What's the problem with this thinking?

* It's focused only on you personally
* No one else features in the world you create for yourself
* The problem is that it doesn't work
* It may seem to work in a carefully controlled society for a while
* But when the storms of life come (and they will) you will not be able to stand against them on your own
* Even when things are going well, you won't be able to build anything substantial unless your life goes beyond simply looking out for number one

You may say, but Alex, are you now trying to seel us communism

* No because communists try to force collective structures on people
* Whereas when I look at the world and history I realize that the idea of working together only works when people choose, out of their own free will, to work together and build something together

The idea of free will is super important here! People need to choose to collaborate

* This workshop is about helping people gain the tools they need to build relationally


