== The Role of Fathers

=== How to treat children

[quote, Ephesians 6:4 KJV]
____
And, ye fathers, provoke not your children to wrath: but bring them up in the nurture and admonition of the Lord.
____

Paul instructs fathers not to provoke or annoy their children.
The Greek word for this is **parorgizete** which is similar to frustrate or provoke to anger.
Fathers should avoid excessive teasing, any form of belittling, favouritism, cruelty, brutality, unfairness etc.
Often I have seen Fathers in the name of fun or joking around annoy, frustrate and emotionally hurt their children.
At the time they think this is funny, but they often don't realize they are hurting their children deeply.
This can cause them to build up anger towards their Father as they feel unloved and abused and of little value.
Don't forget how much your children draw from you in terms of love and identity.
If you constantly make them feel worthless they may take on this identity and may end up hating and despising you for it.

[quote, John Piper]
____
Fathers . . .

bring them up (ektrephete auta)

in the discipline (paideia)

and instruction (nouthesia)

of the Lord (kuriou).
____

How do we instruct our children in the "nurture and admonition of the Lord"?

