=== Email 3
Good evening,

Here's a list of pre-course reading - please take a look at this material if you can. Please think about how these might relate to facilitation

Facilitator mindset:
https://www.linkedin.com/pulse/crafting-success-facilitators-mindset-hannah-baker-ceqze/

Facilitator ethics:
https://www.iaf-world.org/site/pages/statement-values-code-ethics-0

Emotional intelligence (a free workbook from the University of Nottingham):
https://training.nottingham.ac.uk/Public/Emotional-Intelligence-Workbook.pdf

We will not be using the activities from the EI workbook as such but it contains a useful introduction to the topic.

The ACS-CF Workbook is attached. It contains brief notes on many different aspects of facilitation (including the above). On the first day we plan to cover up to and including Facilitation Agreements (page 19).

Our approach is distilled from these key resources amongst others. You are not expected to have read these!:

Roger Schwarz, The Skilled Facilitator
Jean Tabaka, Collaboration Explained
Sam Kaner et al, Facilitator's Guide to Participatory Decision Making
Friedrich Glasl, Confronting Conflict

We look forward to seeing you on Wednesday.

Best regards,

Simon and Barbara


=== Email 2
Hello,

Thank you for booking a place on our online Agile Coaching Skills-Certified Facilitator Course next week 13-15 March (Wednesday-Friday). We plan to run the sessions from 9-15 GMT / 10-16 CET each day.

Here's a link to the Zoom meeting:

Topic: Online Agile Coaching Skills-Certified Facilitator Course

Join Zoom Meeting

https://us02web.zoom.us/j/84639034489?pwd=WFBsYUdYYzB3OUVEWU5SUEw3eWp3dz09

Meeting ID: 846 3903 4489
Passcode: 246229

Please make sure you have a good internet connection, good audio and a webcam available.

There is no formal preparation needed for the course. We will be sending out a PDF of the course workbook on Friday and there is some optional reading in the workbook. Details will be provided along with the workbook PDF.

We look forward to seeing you next week. Please let me and/or Barabara know if you have any questions or concerns.

Best wishes,

Simon and Barbara

=== Email 1
Hi,

We are holding our inaugural online Scrum Alliance Agile Coaching Skills-Certified Facilitator (ACS-CF) course and would love it if you could join us as our guest on 13th-15th March 2024.

The course is a deep-dive on facilitation and is relevant for Scrum Masters, coaches and anyone who facilities (e.g. project managers, workshop facilitators etc.), not just in an agile context.  This is our first ACS-CF and before we roll it out with further dates, we want to fine-tune it. 

The course will be facilitated by Simon (Certified Scrum Trainer) and Barbara (ICF Accredited Coach and ScrumCenter’s Scrum Master).

As our guest, there will be no charge and it includes certification for those eligible (see attached course data sheet for certification requirements).

We appreciate it’s a large commitment in time (3 shortened days so you can do other stuff as well!) and we can guarantee you a fun and valuable experience.

Here’s a link to our course webpage for more information:

scrumcenter.co.uk/certified-facilitator-training-course/

Please let us know if you can attend by replying to this message. Please feel free to ask any questions.

Best regards,

Simon


