
== The Gospel of the Kingdom is an answer to...

=== Good News
All of humanity lives under the oppression of fear: the ultimate fear being death itself. Most people are constantly trying to protect the lives they have created for themselves and those they love, afraid they may "lose it all!". Others pretend to show false bravado by pushing their limits to show they aren't afraid of death or injury, but this is often an attempt at running away or an attempt to fight or face their fear. The fear is always there. And in the end when no one is around, and there is nothing to distract, we stare into the abyss of death afraid of what lies beyond that door.

Many may wonder if there is a life after death. If so is there a God? If I meet him face to face will I be judged for the way I lived my life? Just in case, many try to live what they deem to be a good life, others go in search of God to see if they can find Him in this life, but many give up once they are blinded by the many religious options and the hypocrisy they see in those that say, "Go this way…"

Tormented and confused as though by demons, we rush our way through our lives trying to avoid these questions. We may triumphantly declare, "I am an Atheist!" and applaud ourselves for our courage to throw off primitive ideas about God, the after life etc. We sing along with the chorus of, "Enjoy your life because soon you will die and cease to exist having played your part in the evolutionary process!"

At first we indulge in our parties and frivolous lives, but as time passes our hunger for eternal purpose and meaning gnaws at us like the hunger after a joint. We try every new experience, trend and idea, but we are only left with shame and fear. Shame attacks us like a rabid dog, hounding us, never ceasing until we our sanity is lost and once again we stare into that dark abyss: death who seems to welcome us like a pack wolves into their den.

We frequent the shrink parlour or any other parlour clamoring for hope or trying to distract ourselves withe idea that this is normal and I am OK. Everyone else is as crazy as I am, but shortly before we breathe our last breath we clamor for hope, but alas it is too late, displayingdeath has come to collect us.

Can we escape the inescapable? Is there hope?

Hope is to be found in an old story you may have heard as a child. There was once a man born of a Virgin, the Son of God, Jesus Christ. He lived a perfect life, dies on a cross carrying all our sin, shame, and fear. Having defeated satan, he took the keys of Hades and arose on the third day displaying his victory over the evil triumvirate of satan, sin and death. He now calls everyone to repent and believe so that we may be saved from the abyss.

This is the good news! This is your hope, if you want it…

=== Fear & Fear of Death

Every human I know is afraid. They live their lives in fear. Most people are constantly trying to protect the lives they have created for themselves and those they love, in fear that they may "lose it all!". Even those who seem courageous, live their lives in fear of not reaching their full potential or fulfilling their dreams. But the thing we live with the most is the fear of death. We fear it so much that most people try to avoid this subject until they are confronted with it by the death of someone they know, or they become sick, or have a near death experience that forces them to deal with the subject.

Regardless of the matter, deep down in side we all fear death in one way or another. We feel were are made to live forever, but we are faced with a finite existence. We live our lives trying to get the most out of our lives before the inevitibility of death comes to have its final say.

But is there a way to cheat death? Is there a way to escape 

=== The need for Affirmation
An issue that plagues us as people is the need for affirmation: the need to "do the right thing" and be affirmed. We have such a deep need for this that we will end up using others in order to fill this need in side. I think of how often charity work is done not out of the impartial motivation of helping others, but out of a deep need within us as humans to help others in order to make ourselves feel better.

=== Shame
When we don't do the right thing we feel shame. This is where secrets start and have their power.
Shame like dark secrets hold us in a form of slavery. We are bound to them, always with the fear that if someone finds out we will "die" from shame: losing our standing, influence, power etc. but ultimately we are afraid of no longer being loved.

=== Hopelessness & lack of vision

Many in the West have lost their sense of vision. The things that drove the West in the previous 200 hundred years was the desire to increase the power of the Nation-State. Since the end of the 2nd World War the West has been searching for a new purpose or vision for life. Some countries experimented with Socialism / Marxism, others with the Individualistic Materialism championed by the American way of life, but all of these have failed to provide a compelling vision of the future. In the last few decades their has been a switch to a focus on Liberalism, Environmentalism and Technologicalism coupled with the desire to become a multi-planetary species. There has also been a backlash against this trend with many religious groups and conservative voices calling for a return to "traditional values" and religions.

These are all once again other forms of "...ism's" that will utlimately not fulfill us as people. In fact like a new toy that is discarded after several months of use, we will find that these paths will still not satisfy us as people even though there is much good, excitement and wonder that we could experience as mankind if we pursue these paths.

However, I am quite convinced that regardlesss of what happens, even when we stand at the edge of our galaxy contemplating the next big leap we will still feel unfulfilled.

Why? Simply because we have forgotten a very simple truth. We are created beings. We were created for relationship with our creator and only in Him can we find our worth and have our being.
