== What went wrong?

We believed a lie.

It began with us humans not taking care to guard the commandment entrusted to our hearts: Eve added to the commandment the Lord had given her. satan with great cunning began to get mankind to question whether or not God had realy said we shouldn't eat of the fruit of the tree. He then began to get us to think God was keeping something good away from us.

By the time he was done we no longer trusted God and filled with pride and the desire to be like God we took that first bite. From that point on death opened its wide, dark arms to embrace us, taking us captive into a life of mistrust, fear, and torture until we breathed our last and where hell itself would then open its embrace to welcome us into an eternity of punishment for our sin. As eternal beings brought to life by the breath the Holy One our existence would never end, and the torture would never end with it.

All throughout history death was the one enemy no man could avoid. Whether embraced with terror or with honour, no man could avoid it, no matter how rich or poor, courageous or fearful, everyone could not escape death.

Men would come up with creeds, rules, regulations that they thought would buy them entrance to paradise, but deep down inside as death beckoned we all know when never live up to these lofty ideals. Though we may sound like heroes at our funerals, the people we lived with know who we really are.

Even amongst the greatest in history: whether philosopher or general, none have lived up to the golden standard they set out to live by. Though their speeches, and writings are filled with lofty pursuits you need only scratch a little before you see that they are simple, broken, men tarnished by sin and without any real hope for their followers. they are the blind leading the blind.

But into this hopeless worĺd a King was born who would finally bring an end to the dispare and make all things new...

