== The Gospel in Short

Mankind was created in the image of the Trinity to steward his Creation. There was one commandment God gave that mankind broke which was to eat from the tree of the knowledge of good and evil. Through this act man was seperated from God and spiritually died. Everything mankind touched or acted on would ultimately lead to death. Though mankind was made to live for eternity and to rule and reign, we found ourselves captive to sin, death and satan.

Then Jesus, the Son of God, was born of a virgin and became flesh (man). He lived a perfect life an example for us to follow once we had been freed fromour captivity. He then paid the ultimate price for our captivity by laying down his life for our sin! On the third day he rose from the dead displaying for all to see that he had overcome sin, satan and death!

He told us that if we simply believed in him we would receive freedom from the captivity that he had overcome, a second chance, a new birth into his life. He would welcome us back into relationship with the Trinity where we would finally be able to become our true selves, destined to rule and reign with Him now and into eternity.

With the new birth we would receive the Holy Spirit: empowering us to do His work on this earth and to prepare the planet for the return of our King: King Jesus!
