== Introduction

"And Jesus went about all the cities and villages, teaching in their synagogues, and preaching the gospel of the kingdom, and healing every sickness and every disease among the people."
-- Matthew 9:35 KJV

Every generation faces its challenges where many are fearful of what will happen today and in the future. We ask ourselves whether or not we have a future or if we will self destruct as a culture.

We watch every move of those declaring what will come next or who are actively involved in getting us there. Nevertheless, we are still left unsatisfied clamouring for more information or more connection so that we don't feel alone as we navigate our way forward.

We also struggle with death. Normally we try to avoid the discussion altogether. Our scientists have not been able to answer the questions of how to prevent death and what happens to us once we die.

Is there hope for us? Will we be able to find answers to the challenges that face us?

Christians express their hope in the message of the kingdom of God.

