== Introduction
The internet has been a blessing and a problem at the same time.
Never before have we had the opportunity to research current and historical moves, teachings and schools of christian like today.
In a few seconds a person can find out the various arguments for or against an argument.
We are able to consume the best and worst teaching from across the globe without leaving our armchair.

[quote, James 1:22 KJV]
____
But be ye doers of the word, and not hearers only, deceiving your own selves.
____

We are probably one of the most likely generations to be hearers and not doers of the Word.
Some enjoy listeing to deep theological debates on various subjects.
Others are looking for the next move of God or man of God who will lead us into the next Revival.

Watching thsi from the sidelines you shouldn't be judged for asking, "What is going on here?"
Where should I give my foucs, how should I live out my Christian walk in these crazy days.
I too have asked myself this question.
I have been disillusioned with every movement of Christianity out there.
None of the moves really says to me, "Yes, this is the way forward for us..."

This book doesn't aim to give answers, but to an opportunity for you to slow down and consider the direction you are moving in.
Questions are more helpful for this situation than providing you with cookie cutter solutions that will only last until the next fad cycle begins.
My hope is that these questions will help you to consider your path and for you to begin to follow Christ the way he beckons you too.
