== Follow Me!

[quote, Mark 1:16-18 KJV]
____
16 Now as he walked by the sea of Galilee, he saw Simon and Andrew his brother casting a net into the sea: for they were fishers.

17 And Jesus said unto them, Come ye after me, and I will make you to become fishers of men.

18 And straightway they forsook their nets, and followed him.
____

To be a disciple is to respond to the call of Jesus to follow him. 
So many christians get bogged down concerning themselves with the intricacy's of theological arguments, the newest anointing, conference, man of God etc.
However, how many of us come back to the simple issue of making a decision to follow Jesus?
We will concern oursleves with all sort's of spiritual issues, but do we ever come to the point where we make the decision to follow Jesus?
We say, "Jesus is my King." But in the simplest thing of choosing to follow him, he is not our King.
We turn our King into our servant: there to fulfill our wants and desires.
But this is not the road of discipleship. If we truly choose to make Jesus our Lord and Saviour, we must choose to put aside our agenda, vision for our lives and follow him.
