== Introduction

I believe that work is a fundamentally built into our core purpose as human beings. A lrgae part of this is bringing order where their is chaos.
Do we always d a good job of this? No! But, nevertheless this is built into our make up and we are driven to create, order, organize etc.

Assuming the value of work has been established,
one of the activities that has occupied most a person's life
is to solve a problem they perceive, but also to ask the question,
"How best do I solve this problem?"

Related to this question are the various related goals that would determine
what the best way of solving the problem is.

This document is a collection of many tools and patterns I have collected along the way to solve various problems that occur in work life.
I hope you find this helpful! Enjoy!

=== Motivation
* I want to teach the core principles of Jesus' message as outlined in the gospels to the World
* I must begin with the Word, Grace, Repentance, Faith
* Then move onto the teachings of the Beatitudes etc.
* e.g. Unpunishable, Humility & Poorness of Spirit necessary to learn
