= Note for Preachers
Hallo Ihr Lieben,

Ich wende mich mit einem Schreiben an euch Prediger der ELIA Gemeinde. Sehr gerne hätte ich mit euch alles persönlich besprochen und erörtert, was sich bei uns in der Gemeinde so alles verändert und wo wir alle auf Veränderungen reagieren müssen.

Da Treffen derzeit nur schwer möglich sind und wir derzeit trotzdem reagieren müssen, schreibe ich euch diese Zeilen.

Wie ihr ja sicher alle mitbekommen habt, sind wir derzeit nur noch im Online Format präsent. Uns fehlt die Gemeinschaft sehr stark. Als Prediger tue ich mir sehr schwer, nur in eine Kamera zu sprechen und nicht zu den Menschen, wie wir es gewöhnt sind. Für einen reibungslosen Ablauf bei so einer Live Sendung bedarf es viel mehr Absprachen, wie sonst bislang bei uns üblich.

Es braucht einen noch intensiveren Dialog zwischen Gottesdienstleiter, Lobpreisleiter, Tontechnik, Kameratechnik und natürlich Prediger.

Was ist derzeit besonders wichtig?

Predigt Thema:

Als Prediger wäre gut, wenn wir unser Thema zwei Wochen vorher mit dem Gottesdienstleiter und dem Lobpreisleiter besprechen.

Übergänge besser gestalten:

Wenn z.B der Lobpreis nach der Predigt statt finden soll, braucht die Band ca 5 Minuten um sich anzuschließen und startklar zu sein. Längere Wartezeiten kommen im Online Format nicht gut an. Wenn der Lobpreis zu erst kommt, ist mit dem Lobpreisleiter zu besprechen wann ihr schon auf die Bühne sollt. Es können auch musikalische Übergänge eingeplant werden, das sollte lediglich im Vorfeld mit einander geklärt sein. Eine Rücksprache über euer Vorhaben sollte auch mit der Tontechnik erfolgen.

Technische Klärung:

Spätestens 09:00 im Gemeinde Gebäude erscheinen. Sound-check und Micro ausprobieren. Sofern es sich nicht um ein Ansteckmicro handelt, ist das Micro in einem festen Abstand zu halten. Da es sonst im Netzt zu starken Lautstärken Schwankungen führt. Die Tontechnik wird euch da einweisen.

Power Point:

Wenn ihr eine Power Point nutzen wollt, muss diese bis spätesten Mittwoch bei Sascha Zeller landen. Damit er das für Sonntag passend machen kann. Power Point die erst am Sonntag eingereicht werden, können nicht mehr verwendet werden.

Kamera:

Sascha, bzw. der verantwortliche Kamera Regisseur weist euch ein, in welche Kamera ihr sprechen könnt, damit sich der Zuschauer auch angesprochen fühlt. Es ist auch wichtig, sich im Lichtkreis auf der Bühne zu bewegen, damit ihr auf dem Bildschirm auch im „Lichte wandelt“.

Absprachen:

Derzeit ist es besser lieber häufiger miteinander zu sprechen, als zu wenig.

Vielen Dank Euch für euren Dienst. Lasst uns mehr denn je, darauf achten, dass es uns gelingt, Menschen miteinander zu verbinden, die äusserlich getrennt sind. Danke, dass ihr Herzensnähe untereinander schafft.

Wir brauchen in dieser besonderen Zeit alle das Gefühl, dass wir nicht allein sind sondern zu einem lebendigen Organismus, zum Leib Christi und der Gemeinschaft der Heiligen gehören.

Lasst Euch vom Heiligen Geist inspirieren wie wir diese Kluft derzeit überwinden können. Damit wir gestärkt und nicht geschwächt aus dieser Zeit hervorkommen werden.

Wir achten und schätzen euch und eure Mitarbeit im Reich Gottes und wünschen euch von ganzem Herzen viel Gnade und Gunst bei eurer Vorbereitung.

Sollten Fragen auftauchen, sprecht mich oder die Verantwortlichen an.

In Liebe, Heinrich
