= Daniel

== Daniel 1
* if we want to be able to speak into the culture of our day we will need to learn the language and literature of the culture.
* Daniel and his companions underwent a test whether they would stay true to God's ways or just go with the flow.
** Though we are called to understand the surrounding culture we are not called to go with it.
** Daniel sought permiasion...
*** Notice though how Daniel says, "no". Look how he hands out an olive branch to the person he is under authority of. Though he stays true to his conviction he also ensures the overseer reaches his goal of preparing them for the King's service.
* Not sure how we should interpret their new Babylonian names?

== Learnings from the Life of Daniel
* Let's look at the life of Daniel to better understand what I believe the call is to this generation
* Daniel stood up for his values, but handed out an olive branch to solve the problem of the person he was under authority
* Though Neb. killed many Jews and destroyed the Kingdom of Judah, Daniel served him with the utmost respect
* We need Discipline in Prayer and our lives.
** One of my heroes of the Faith - Derek Prince - said that the one thing he would say to the younger generation is to get discipline!
** Can you imagine if we started praying 3 times a day!
* Your normal work day is the call to a supernatural life.
** Ask God to do supernatural things in the natural
* Seek to beomce the head and not the tail
** I love the way in which Israelis / Jews always end up getting to the top of a culture where they establish themselves
*** Read the Book "Startup Nation" if you want to understand what I mean
** This isn't just God's blessing, but also a mindset in their culture
* Daniel's perseverance caused the very King who his people probably hated to change and eventually acknowledge that the Lord is God
** To put this in context, it's as if there was perhaps a Jew that served in Hitler's Cabinet and who eventually got Hitler to repent and turn to Jesus.