= Galatians

== Summary


== 1

== 2

== 3
=== vs. 1-3
The Galatians had been deceived by the Judaizers into thinking they needed to follow the Law in order to be righteous. Paul asked if they had received the Holy Spirit and thus the accompanying salvation through their own works or by believing in the Jesus.

=== vs. 4
TODO: Why did he ask if they had suffered so many things in vain?

=== vs. 5 - 6
Paul asks them if the Trinity who gave them the Holy Spirit and who does miracles (e.g. healings, deliverance etc.) amongst them does it because of their so called righteous deeds or because of they simply believe. Never forget everything we receive in the kingdom is by faith directed towards the Trinity.
TODO:what does the hearing of faith mean?
paul reminds them that because Abraham believed that God would fulfill his promise that he was accounted (given) righteousness. Of course this righteousness would be paid for in the future by Jesus's death and resurrection, but God lives outside of time and knowing what He would do in the future He was able to declare that Abaraham was now righteous.
