== 2024-10-27 Neu geboren: Kind Gottes werden

=== Der Wunsch nach Vollkommenheit

* *Geschichte der Antike:* strebten viele die Menschen ein "gott" zu werden z.b. Alexander der Große
* *Selbstoptimierung in Religionen / Philosophien:* viele Religionen lehren, Perfektion durch eigene Anstrengung zu erreichen.
** Buddhismus, Hinduismus, Stoizismus, Konfuzianismus, Sikhismus, Jainismus, Islam.
* *Nietzsche und der "Übermensch":* Idee eines idealisierten, selbstbestimmten Individuums.
** *Selbstüberwindung und Wachstum:* Ermutigt Menschen, Instinkte und Individualität anzunehmen.
* *Marx und die perfekte Gesellschaft:* Suche nach einer utopischen, gerechteren Welt.
* *Moderne Selbstoptimierung:* Bücher, Social Media und Programme zur "perfekten Version von uns".

=== Problematisches Resultat

* *Schlechte Früchte:* Die Umsetzung dieser Ideen führte zu schlimmem Leid.
* *Einfluss auf Nazis:* Nietzsches Ideen beeinflussten das nationalsozialistische Gedankengut.
* *Kommunistische Tragödien:* Versuch, perfekte Gesellschaft zu schaffen, endet oft in Gewalt.
* *Selbstoptimierung und Narzissmus:* Streben nach Perfektion fördert Narzissmus und gesundheitliche Störungen.
* *Fortschritt und Naturzerstörung:* Wissenschaftlicher Fortschritt schadet oft der Natur.
* *Ironie des Bösen:* Viel Unheil wurde von Menschen verursacht, die das Gute wollten.

=== Das tiefe Problem

* *Zerstörerische Spirale:* Je mehr wir verbessern wollen, desto schlimmer wird es.
* *Rückkehr zu Eden:* Ursprung des Problems liegt im Garten Eden.
* *Wirkliches Ereignis:* Der Fall Adams und Evas ist keine Metapher, sondern ein realer Wendepunkt.
* *Ungehorsam gegen Gott:* Sie verließen Gottes Führung, um selbst zu entscheiden.
* *Gebrochenheit des Menschen:* Seitdem ist die Menschheit in einem Kreislauf gefangen.
* *Sünde ist:* Rebellion gegen den Willen Gottes
* *Führt zu:* geistlichem Tod und Versklavung
* *Du kannst nicht:* dich aus diesem Problem herausarbeiten

=== Die Lösung: Jesus Christus

* *Gottes Liebe:* Gott sendet Jesus, um das Problem zu lösen.
* *Nikodemus und das Problem:* Nikodemus sucht Perfektion durch eigene Anstrengung.
* *Jesu Antwort:* "Du musst neu geboren werden!"
* *Zurück zum Baum des Lebens:* Weg vom Baum der Erkenntnis hin zu wahrem Leben.
* *Notwendigkeit der Neugeburt:* Nur durch Wiedergeburt ist ein Ausweg aus dem Kreislauf möglich.

=== Bedeutung von „Wiedergeboren“

* *Neu geboren:* Geistliche Wiedergeburt durch Gottes Geist
* *Transformation:* Keine Selbstverbesserung, sondern Erneuerung
* *Gottes Königreich:* wir in den Zustand zurückkehren können, in dem unser ganzes Wesen unter seiner Herrschaft leben kann
* *Wiederhergestellte Beziehung:* Rückkehr zu Gott, wie im Garten Eden
* *Werk des Heiligen Geistes:* Veränderung nur durch den Geist möglich
* *Neue Identität:* Vom Sklaven der Sünde zum Kind Gottes
* *Wahrer Zweck:* Berufung in Gottes Familie und Auftrag

=== Warum „Wiedergeboren“?

* *Eine völlig andere Welt!*
** *Meer vs. Wüste:* Kann direkt in / neben Gottes Reich sein und es dennoch nicht erfassen.

* *Wiederherstellung der Gemeinschaft:* Zurück zur innigen Beziehung mit Gott.
** *Kind Gottes:* wir sind in Gottes Familie als seine Kinder aufgenommen
* *Wahrer Frieden:* Echte Verbundenheit mit Jesus und tiefer Frieden.
* *Ewige Gemeinschaft:* Als seine durch den Geist bestätigten Kinder werden wir die Ewigkeit mit dem Herrn genießen.

* *Freiheit von Sünde (1 John 3:9):* Neu Geborene sind keine Sklaven der Sünde mehr.
** *Echte Entscheidungsfreiheit:* Fähigkeit, Sünde zu widerstehen und wirklich Gutes zu tun.
** *Vorher gefangen:* Vor der Neugeburt waren gute Absichten oft erfolglos.
** *Autorität über Sünde:* Durch Jesus haben wir Macht, Sünde abzulehnen.

* *Geistliche Wahrheiten erfassen:* Neu geboren bedeutet, Gottes Wahrheit zu erkennen.
** *Göttliche Perspektive:* Wie eine Brille, die das Leben klarer sehen lässt.
*** Wie eine Wüste neben einem Ozean kann man einen Ort ohne Leben
*** direkt neben einem Ozean haben, der von Leben wimmelt
**** Was du nicht sehen kannst, wenn du nur aufs Land schaust

* *Die Stimme des Hirten hören:* Das Herz wird empfänglich für Gottes Führung.
** *Folgt seinem Weg:* wie es ursprünglich im Garten sein sollte

=== Zeichen der Wiedergeburt

* *Woher wissen wir, ob wir wiedergeboren sind?*

* *Neue Freude:* Tiefe, anhaltende Freude und Frieden (Römer 15:13)
* *Veränderte Prioritäten:* Gott steht im Mittelpunkt, nicht das eigene Ich (Matthäus 6:33)
* *Neues Verlangen nach Gottes Wort:* Starker Hunger nach der Bibel und dem Gebet (1. Petrus 2:2)
* *Liebe für andere:* Aufrichtige Liebe und Mitgefühl für Mitmenschen (1. Johannes 4:7)
* *Abneigung (Hass) gegenüber Sünde:* Tiefe Ablehnung von Sünde und bösen Taten (Römer 12:9)
* *Innerer Friede:* Frieden, der durch Umstände nicht zerstört werden kann (Philipper 4:7)
* *Vergebung:* Bereitschaft, anderen zu vergeben, wie Christus vergeben hat (Epheser 4:32)
* *Vertrauen auf Gott:* Tieferes Vertrauen in Gottes Führung und Plan (Sprüche 3:5-6)
* *Wachsendes geistliches Verständnis:* Besseres Verstehen geistlicher Wahrheiten (1. Korinther 2:12-14)
* *Frucht des Geistes:* Zeichen wie Geduld, Freundlichkeit und Selbstbeherrschung (Galater 5:22-23)
* *Zeugnisbereitschaft:* Wunsch, anderen von Jesus zu erzählen (Apostelgeschichte 1:8)
* *Erneuerte Identität:* Selbstbewusstsein als Kind Gottes, angenommen und geliebt (Johannes 1:12; Römer 8:15-16)

* *Taufe:* Das "äußere" Bild!
** *Äußerer Ausdruck innerer Wandlung:* Die Taufe zeigt den Wunsch nach einem neuen Leben.
** *Identifikation mit Christus:* Die Taufe ist ein Symbol für den Tod des alten, toten Menschen, der in der Sünde gefangen ist, und die Geburt eines neuen Lebens in Christus, das durch seinen Tod und seine Auferstehung am Kreuz vorbereitet und ermöglicht wurde.

=== Unterschied zwischen Gerechtigkeit und Wiedergeburt

* *Rechtfertigung und Wiedergeburt:* Zeitlich untrennbar, aber dennoch verschieden
* *Gottes Werk für uns:* In der Rechtfertigung tut Gott etwas für uns
* *Gottes Werk in uns:* In der Wiedergeburt wirkt Gott in uns
* *Äußere Beziehung zu Gott:* Rechtfertigung ändert unsere Stellung; von Feinden zu Kindern
* *Innere Veränderung:* Wiedergeburt verwandelt die Seele; von Sündern zu Heiligen
* *Gottes Gunst:* Rechtfertigung stellt uns in Gottes Gunst wieder her
* *Gottes Bild:* Wiedergeburt formt uns nach Gottes Bild
* *Schuld und Macht der Sünde:* Rechtfertigung nimmt die Schuld, Wiedergeburt die Macht der Sünde
* *Gleichzeitig, doch verschieden:* Zeitlich verbunden, aber unterschiedliche Naturen

=== Der Unterschied zwischen der Wiedergeburt und der Erfüllung mit dem Heiligen Geist

* *Johannes 1:12 ELB:* ...so viele ihn aber aufnahmen, denen gab er das Recht, Kinder Gottes zu werden, denen, die an seinen Namen glauben;
** Recht - exousia (authorität)
* *Apostelgeschichte 1:8 ELB:* Aber ihr werdet Kraft empfangen, wenn der Heilige Geist auf euch gekommen ist; und ihr werdet meine Zeugen sein, sowohl in Jerusalem als auch in ganz Judäa und Samaria und bis an das Ende der Erde.
** Kraft - dunamis (Kraft, Stärke
* *Die Jünger wurden wiedergeboren:* Sie waren Kinder Gottes, befreit von der Sünde.
** Jesus hatte ihnen bereits den Heiligen Geist eingehaucht (Johannes 20:22)
* *Die Jünger brauchten Kraft:* Sie brauchten etwas mehr, um wirksame Zeugen zu sein und das Evangelium vom Reich Gottes in Kraft zu verkünden

=== Kann jemand, der wiedergeboren ist, immer noch sündigen?

* *Wiedergeboren, aber nicht ohne Sünde:* Die Schrift behauptet nicht, dass ein wiedergeborener Christ niemals sündigen kann
* *Neue Natur:* In jedem wiedergeborenen Christen entsteht eine völlig neue Natur
* *Pauls Begriff:* Der „neue Mensch“ steht im Gegensatz zum „alten Menschen“
* *Der alte Mensch:* Verdorben, gefallen, beherrscht den nicht Wiedergeborenen
* *Völliger Gegensatz:* Der „neue Mensch“ ist gerecht und heilig; der „alte Mensch“ ist verdorben und verderbt
* *Natur des neuen Menschen:* Als von Gott geboren, kann der „neue Mensch“ nicht sündigen
* *Natur des alten Menschen:* Produkt des Falls, unfähig, nicht zu sündigen
* *Wechselspiel der beiden Naturen:* Das Leben eines wiedergeborenen Christen ist ein Resultat dieses inneren Kampfes
* *Unterordnung des alten Menschen:* Solange der „alte Mensch“ unterworfen ist, herrschen Gerechtigkeit, Sieg und Frieden
* *Wiedererstarkung des alten Menschen:* Wenn der „alte Mensch“ die Kontrolle gewinnt, folgen Niederlage und Sünde
* *Zusammengefasst:* Ein wahrer Christ kann durch das unvergängliche Wort Gottes völligen Sieg über die Sünde erlangen
* *Der nicht Wiedergeborene:* Hat keine Wahl außer der Sünde; ein Sklave seiner gefallenen Natur

=== Wie werden wir wiedergeboren?

* *Eine glaubens erfüllte Antwort auf das Wort (Jakobus 1:18, 1. Petrus 1:23):* Indem man auf das Wort im Glauben antwortet
* *Wir müssen eine persönliche Antwort auf das Evangelium geben...*
** *Christus und das Kreuz:* Der Vater übergab Christus zum Tod für unsere Sünden
** *Christus begraben:* Der Herr wurde in das Grab gelegt
** *Auferstehung:* Gott erweckte Christus am dritten Tag zum Leben
* *Gerechtigkeit durch Glauben:* Gerechtigkeit kommt durch den Glauben an diese Tatsachen
** *Persönliche Antwort:* Jeder muss eine direkte, persönliche Antwort an Christus geben
* *Antwortmöglichkeiten:* Den Namen Christi als Herrn anrufen, zu Christus kommen, Christus empfangen, das Wasser des Lebens trinken, das nur Christus geben kann

=== Ruf zur Entscheidung

* *Bist du neu geboren?* Hast du Gottes Einladung zur Neugeburt angenommen?
* *Viele Kirchenmitglieder brauchen die Neugeburt:* Wie Nikodemus, der versuchte, aus eigener Kraft ein guter Mensch zu sein.
** Viele kulturelle Christen gebrauchen eine Neugeburt
* *Frage an Dich:* Hast du diesen Tatsachen geglaubt? Hast du eine persönliche Antwort gegeben?
* *Einladung zum Gebet:* Wenn nicht, bete jetzt mit mir
** *Gebet:* Herr Jesus Christus, ich glaube, dass Du für meine Sünden gestorben bist, dass Du begraben wurdest und am dritten Tag auferstanden bist. Ich bereue meine Sünden und komme zu Dir für Barmherzigkeit und Vergebung. Im Glauben an Dein Versprechen nehme ich Dich als meinen Erretter an und bekenne Dich als meinen Herrn.
* *Wähle Leben:* Entscheide dich für Jesus, wende dich ab vom alten, verlorenen Selbst.
* *Ein neues Leben, eine neue Familie:* Gott lädt dich ein, Teil seiner ewigen Familie zu werden.
