== 2024-02-16 Elia: Herren Grillabend

=== Ich kam nach Deutschland mit der Erwartung...
* eine wohlhabende und reichhaltige Nation
* eine Nation voller glücklicher Familien
* eine Nation, die die Grenzen von Wissenschaft und Technologie vorantreibt
* eine Nation mit schöner Natur, Architektur, Mode...
* eine Nation mit einer schönen Kultur und Geschichte
* eine Nation des Forschens, des Lernens und der offenen Debatte

=== Aber was habe ich gefunden...
* eine gottlose Nation
* eine Nation, die mit Bordellen und einem Zentrum der Prostitution gefüllt ist
* eine Nation, die Wahrheit und Gerechtigkeit nicht mehr kennt
* eine perverse Nation von Menschen, die sich in der Wahnvorstellung von mehreren Geschlechtern und sexuellen Orientierungen verloren haben
* eine Nation, die die Wahrheit zum Schweigen bringt, indem sie jede Idee, die nicht in das akzeptierte Narrativ passt, als falsch bezeichnet
* eine Nation, die den Anschein von Wohlstand erweckt, aber geistig und moralisch verarmt, korrupt und gebrochen ist
** wie ein Waisenkind, das es geschafft hat, Gold zu finden und sich wie ein Prinz zu kleiden, aber innerlich immer noch ein Waisenkind ist.

=== Aber was mich am meisten beunruhigt hat...
* sind die vielen Männer in den Kirchen der Nation
** Feiglinge, denen es an Mut fehlt
** oder zu sehr damit beschäftigt sind, mehr und mehr materiellen Reichtum zu sammeln
** und sich nicht für die Ausbreitung des Reiches Gottes einsetzen

=== Was wird nötig sein, damit wir aufwachen?
* Wie schlimm müssen die Dinge werden, bevor wir...
** vom Sofa aufstehen
** den Fernseher, das iPad, das Handy, die Playstation ausschalten...?
* Werden wir als eine Generation bekannt sein, die versagt hat, Gottes Ziele zu erreichen?
* Ich will mich nicht schämen, wenn ich meinem Retter von Angesicht zu Angesicht begegne

=== Ich kam nach Deutschland
* Um eine mächtige Armee von Heiligen Kriegern zu suchen
* Eine Armee, die in der Kraft des Herrn ausziehen würde, um die Richtung dieser Nation zu ändern!
* Gott möchte, dass du dich in seine Armee einschreibst!

=== Aber ich fühle mich nicht stark genug
* Gideon
* Für eine solche Zeit wie diese
* Mein Leben ist ein Chaos! Dann bring es in Ordnung
* Unser Feind hat Angst vor den folgenden Menschen...
** Sie haben mit dem Blut des Lammes und den Worten ihres Zeugnisses gesiegt
** Sie haben ihr Leben nicht bis zum Tod geliebt

=== Aber Alex...
* Ich bin so müde
** Ich akzeptiere das nur von Leuten mit kleinen Kindern
** Hört auf, bis 2:00 Uhr morgens aufzubleiben und Netflix zu schauen oder mit der SE zu spielen

> 31 Aber die auf den HERRN hoffen, gewinnen neue Kraft; sie heben die Schwingen empor wie die Adler, sie laufen und ermatten nicht, sie gehen und ermüden nicht.
> -- Jesaja 40:31 ELB


* Ich habe keine Zeit
** Was hat dich so beschäftigt?
** Warum liebst du dein Leben mehr als du Jesus liebst?
** Ich muss mein 2. und 3. Haus in Spanien und meinen BMW abbezahlen

* Ich warte darauf, dass der Herr mich ruft
** Jonathan und sein Waffenträger...
** 1 Samuel 14

** Wir müssen unsere Prioritäten richtig setzen

=== OK, also Alex, was soll ich deiner Meinung nach tun?
* Finde eine Gruppe von Brüdern und ein Gebiet, das du für das Königreich einnehmen kannst.
* Moderne Begriffe: Freunde was sind bereid für dich zu sterben und ein königreichs Projekt

=== Buße
* Wenn ein Prediger die Menschen zur Umkehr aufruft, gibt es normalerweise
** gibt es Weinen und Bekenntnis
** Und so wichtig es auch ist, den Herrn um Vergebung zu bitten
** ist es wichtiger, eine Entscheidung zu treffen und zu planen, was man tun wird, um seine aktuelle Richtung zu ändern
* Also holt alle eure Handys heraus
* Öffnet eure Notiz-App
* Wir werden die nächsten 5' damit verbringen, konkrete Handlungen aufzuschreiben, was wir ändern werden.
* Schreibt konkrete Maßnahmen auf, die ihr ergreifen wollt, um zur Ausdehnung des Königreichs beizutragen.
* Beispiele:
** Nimm täglich den Bus zur Arbeit, damit du das Evangelium weitergeben kannst
** Gehen Sie in die Politik
** Gehen Sie mit Ihrem Reich in die Geschäftswelt
** ...
* Wenn Sie den Namen Jesu nicht in Ihrem Projekt aussprechen, können Sie das Reich Gottes nicht ausbreiten - wir müssen radikal werden, denn die Zeiten verlangen nach Radikalität

* Nutzen Sie diesen Abend, um Männer zu finden, die das gleiche Herz haben wie Sie und verabreden Sie sich innerhalb der nächsten 2 Wochen zu einem weiteren Treffen.
* Nicht um darüber zu reden, wer erfolgreich ist, sondern um Ihr Herz, Ihre Herausforderungen, Siege und Misserfolge zu teilen...
