= Holy Spirit

== Baptism in the Spirit

=== Things accompanying salvation

[quote, Acts 8:15 KJV]
____

15 Who, when they were come down, prayed for them, that they might receive the Holy Ghost:
____

[quote, Acts 10:44 KJV]
____
44 While Peter yet spake these words, the Holy Ghost fell on all them which heard the word.
____

* Doesn't have to happen in any specific order and you don't need the laying on of hands...

[quote, Acts 19:1-7 KJV]
____
1 And it came to pass, that, while Apollos was at Corinth, Paul having passed through the upper coasts came to Ephesus: and finding certain disciples,

2 He said unto them, Have ye received the Holy Ghost since ye believed? And they said unto him, We have not so much as heard whether there be any Holy Ghost.

3 And he said unto them, Unto what then were ye baptized? And they said, Unto John's baptism.

4 Then said Paul, John verily baptized with the baptism of repentance, saying unto the people, that they should believe on him which should come after him, that is, on Christ Jesus.

5 When they heard this, they were baptized in the name of the Lord Jesus.

6 And when Paul had laid his hands upon them, the Holy Ghost came on them; and they spake with tongues, and prophesied.

7 And all the men were about twelve.
____

* These men were clearly believers and saved, but something was lacking...
** Baptism in the name of the Lord Jesus
** Being Baptized in the Holy Spirit the evidence of which being tongues and prophecy
* Here we see that it is normal for people toobtain the gift of Tongues and the Holy Spirit by the laying on of hands

=== Additional Infilling
* Apostles already believed in Jesus and He breathed on them to receive the Spirit

[quote, John 20:21-22 KJV]
____
21 Then said Jesus to them again, Peace be unto you: as my Father hath sent me, even so send I you.
22 And when he had said this, he breathed on them, and saith unto them, Receive ye the Holy Ghost:
____

* Then in Acts 2 they are filled with the Holy Spirit

[quote, Acts 2:1-4 KJV]
____
1 And when the day of Pentecost was fully come, they were all with one accord in one place.
2 And suddenly there came a sound from heaven as of a rushing mighty wind, and it filled all the house where they were sitting.
3 And there appeared unto them cloven tongues like as of fire, and it sat upon each of them.
4 And they were all filled with the Holy Ghost, and began to speak with other tongues, as the Spirit gave them utterance.
____

* Be continuously filled - How were Peter, John & others anointed again with the Spirit

[quote, Acts 4:30-33 KJV]
____
31 And when they had prayed, the place was shaken where they were assembled together; and they were all filled with the Holy Ghost, and they spake the word of God with boldness.
32 And the multitude of them that believed were of one heart and of one soul: neither said any of them that ought of the things which he possessed was his own; but they had all things common.
33 And with great power gave the apostles witness of the resurrection of the Lord Jesus: and great grace was upon them all.
____
