= Fulness in Christ
* I grew up in a culture of fear of lack
** Not having enough to pay off the loans my Mother had taken to run her business
* Even though we were wealthier than most in South Africa, I always had the feelibg we were poor
* I see the Orphan Spirit in the World aeound and I see it so prevalent in Germnay - stinginess
** Restaurants where they don't even give you the ketchup for free - you have to pay extra for it...
** Portions
** You go on holiday with friends and you cout out exactly who spent what
* Buildings are only renovated on the inside as the outside would only matter to others
* Stinginess is linked to jealousy
* People are jealous when you get ahead
** People want to know what you earn and if you earn more, how, because obviously you are doing donethibg dodgy or they are getting cheated in life...
* Churches are jealous of each other...
** We spend more time fighting each other or with infighting than doing what Jesus asked us to do


== Edit in
= Fulness in Christ
== So many living as orphans: Lack
* I grew up in a culture of fear of lack
** Not having enough to pay off the loans my Mother had taken to run her business
* Even though we were wealthier than most in South Africa, I always had the feelibg we were poor
* I see the Orphan Spirit in the World aeound and I see it so prevalent in Germnay - stinginess
** Restaurants where they don't even give you the ketchup for free - you have to pay extra for it...
** Portions
** You go on holiday with friends and you cout out exactly who spent what
* Buildings are only renovated on the inside as the outside would only matter to others

== Stinginess
* Stinginess is linked to jealousy
* People are jealous when you get ahead
** People want to know what you earn and if you earn more, how, because obviously you are doing donethibg dodgy or they are getting cheated in life...
* Churches are jealous of each other...
* People are jealous of each other in the Church

== What we have in Christ: Fulness