== 20201023

=== Dream
Last night I had a dream that I inherited our house from my Dad on Cowley Street. There had been an evil squatter woman who had lived in the one half of the garage and we had finally gotten rid of her
and were able to start clearing up the mess in her space. I realized that the whole house was being renovated and very expensive furnishings were bing built in everywhere; however, I realized that the renovations were being done for another powerful woman and that this house was no longer my house. Whererver I went in the house this woman harrassed me and constantly followed me not giving me a moments peace.

I asked the Lord about this on the way to work and I had a feeling this was a spirit of sexual impurity, the spirit behind the goddess (demon) https://en.wikipedia.org/wiki/Diana_%28mythology%29[Diana] that had stolen my inheritance.

Diana is the Roman goddess equivalent of the Roman Artemis. She is known as the patroness of the countryside, hunters, crossroads, and the Moon. Diana had Lucifer as her consort in medieval and modern traditions. They had a daughter together. So this demon is dangerous if it wants my inheritance.

I repent of comparing the Holy Spirit to Diana.

I realized that I need to repent of sexual impurity, lust etc. and that I had to make a focused effort to get free of this spirit so that it won't steal my inheritance.

How? Simple. Spend more time in the presence worshipping the Trinity. Lucifer and his host ultimately desire worship. Thats why the ancients under their influence would build temples to them to worship them.

One of the biggest backlashes to Paul's Ministry took place in Ephesus concerned the worship of Diana (Acts 19). A silversmith who made images of the goddess Diana and who made good money with this trade started a huge commotion that over took the whole city.

=== End of Secularism & with it Multiculturalism?
* Does Jesus like Secular States?
* Are we in the closing stages of the secular state?
