== Introduction to Team Coaching

=== Where do I even start?
These days there are so many frameworks for teams to choose from, promising lightning fast productivity, efficiency and exuberant team happiness! It is very difficult for anyone new to forming, coaching or leading teams to decide where to start.

What you have in front of you is a collection of my notes gathered over many years of coaching teams that I hope may help you on your journey.

=== Be Warned! Disclaimer!
These notes are based on the assumption that you value the following when it comes to guiding your team.

* Freedom to take responsibility!
* Intrinsic Motivation
* Self Organization

Essentially, I assume you want your team(s) to run themselves as much as possible so that you can work on more important things...
The idea that the work of management is important, but it should, as much as possible, be done by the people working in the team as much as possible.

=== Focus on key values
The approach I like to take to coaching teams is a "values" based approach. I like to focus on the values that I believe are required to build a self motivated and organized team and the methods, processes, tools etc. that can establish such a team,
