==== Script: Introduction

* *Quick Introduction*
** okrs_01_introduction_001.mp3
In today's video, we're unlocking the power of OKRs—your compass to achieving strategic goals and driving unparalleled success. Join us on this journey as we demystify the art of Objectives and Key Results, empowering you to elevate your organizations' performance and align behind a common purpose.

* *It's a challenge...*
** okrs_01_introduction_002.mp3

I think we have all struggled at some time or another to decide on what takes priority in our lives or what task we should do first.
In this day and age where we have so many options and distractions it's difficult to chart your course towards your desired future and to stay focused on "getting there".

** okrs_01_introduction_003.mp3

This isn't just a problem individuals face, but an issue that every group or organization struggles with and needs to proactively address. 

One of the skills you will need to master to reach your dreams is that of effectively setting goals, working towards them and tracking your progress.

* *Why do we "need" for goals?*

Why do we have a "need" for goals?

The question has always been do we want to allow life to happen to us or for us to shape the outcome of our lives in some manner? Goals are really the fruit of an inner desire we all have to shape our future proactively.

The next interesting question then is how do we do this effectively?

This is really the key question we need to be asking. How do we set goals effectively and work towards achieving them in the best possible way?

There have been various tools and management systems used to set goals and align activity towards those goals throughout the centuries. Recently a relatively new method called "Objectives and Key Results" or OKRs for short has been advertised as the secret recipe in the success of companies such as Intel, Google, Adobe, LinkedIn, and Uber.

So what are OKRs?

The concept of OKRs revolves around setting objectives and defining key results to measure progress towards those objectives.

An objective represents what you want to achieve, while key results are measurable outcomes that indicate progress or success.
For example, if your objective is to increase user engagement, key results could include metrics such as the number of active users or the average time spent on your platform.

The power of OKRs lies in their simplicity and clarity.
They provide a framework for setting ambitious yet achievable goals and aligning teams towards a common purpose.
By implementing OKRs, organizations can foster focus, unity, and velocity in their pursuit of success.

However, there is a disclaimer!

Many organizations think that simply implementing the latest new business process fad will heal all their cultural wounds and blaze a trail to glory!
This cannot be further from the truth!
Success doesn't lie in the method itself, but in whether or not the underlying culture necessary for it to work has been adopted in the DNA of the leaders and the organization.

Of course, successfuly implementing a goal setting method requires effectiveness and efficiency...
doing the rgiht things and doing them right and in this series we will be looking to address all of  the above concerns.
